services:
  mysql:
    image: mysql:8
    container_name: sakila_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sakila
    ports:
      - "5001:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./sakila-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./sakila-data.sql:/docker-entrypoint-initdb.d/2-data.sql

  sqlserver1:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver1
    restart: always
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "5002:1433"
  
  sqlserver2:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2
    restart: always
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "5003:1433"

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Your_password123"
      POSTGRES_DB: postgres
    ports:
      - "5004:5432"

  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "5005:8123"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_PASSWORD=password
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  clickhouse-client:
    image: clickhouse/clickhouse-client:latest
    entrypoint:
      - /bin/sleep
    command:
      - infinity

volumes:
  clickhouse-data: 
