services:
  mysql:
    image: mysql:8
    container_name: sakila_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sakila
    ports:
      - "5001:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./sakila-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./sakila-data.sql:/docker-entrypoint-initdb.d/2-data.sql

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_etl
    restart: always
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "5002:1433"

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Your_password123"
      POSTGRES_DB: postgres
    ports:
      - "5003:5432"
