services:
  etl-sandbox-delta-worker-service:
    build:
      context: ../../../
      dockerfile: Sources/Hosts/EtlSandbox.DeltaWorkerService/Dockerfile
    profiles:
      - apps
    networks:
      - network

  clickhouse-server:
    image: clickhouse/clickhouse-server:25.7.1
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_PASSWORD=password
    networks:
      - network
    ports:
      - "5007:8123"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8123/ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
  
  tabix:
    image: spoonest/clickhouse-tabix-web-client
    depends_on:
      - clickhouse
    networks:
      - network
    ports:
      - "5008:80"

volumes:
  clickhouse-data:

networks:
  network:
    driver: bridge