services:
  etl-sandbox-delta-web-api:
    build:
      context: ../../../
      dockerfile: Sources/Hosts/EtlSandbox.DeltaWebApi/Dockerfile
    ports:
      - "5005:8080"
      - "5006:8081"
    profiles:
      - apps
    networks:
      - network

networks:
  network:
    driver: bridge