services:
  etl-sandbox-beta-web-api:
    build:
      context: ../../../
      dockerfile: Sources/Hosts/EtlSandbox.BetaWebApi/Dockerfile
    ports:
      - "5003:8080"
      - "5004:8081"
    profiles:
      - apps
    networks:
      - network

networks:
  network:
    driver: bridge